# Generated by Django 5.0.1 on 2024-01-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('bodyNews', models.TextField(verbose_name='Новость')),
                ('image', models.ImageField(null=True, upload_to='imageNews/', verbose_name='Изображение')),
                ('like', models.IntegerField(default=0, verbose_name='лайк')),
                ('dizlike', models.IntegerField(default=0, verbose_name='дизлайк')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
