# Generated by Django 5.0.1 on 2024-03-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, db_column='upload_date', verbose_name='дата загрузки'),
        ),
    ]
