# Generated by Django 5.0.1 on 2024-04-08 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_upload_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(max_length=30, verbose_name='автор')),
                ('comment_news', models.TextField(verbose_name='Сообщение')),
                ('date_comment', models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария')),
                ('novosti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
            ],
        ),
    ]
