# Generated by Django 5.0.1 on 2024-04-08 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_comment_novosti'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='novosti',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.news'),
        ),
    ]
