# Generated by Django 5.0.1 on 2024-04-08 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_comment_novosti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='novosti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news'),
        ),
    ]
