# Generated by Django 5.0.1 on 2024-04-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_comment_novosti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Логин')),
                ('password', models.CharField(max_length=30, verbose_name='Пароль')),
                ('email', models.EmailField(max_length=200, null=True, unique=True, verbose_name='E-mail')),
                ('first_name', models.CharField(max_length=30, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, null=True, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='Телефон')),
                ('image', models.ImageField(null=True, upload_to='imageUsers/', verbose_name='Изображение')),
                ('date', models.DateTimeField(auto_now_add=True, db_column='date', verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
