# Generated by Django 5.0.1 on 2024-01-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameProgramm', models.CharField(max_length=50, verbose_name='Название программы')),
                ('bodyProgramm', models.TextField(verbose_name='Программа тренировок')),
            ],
            options={
                'verbose_name': 'программа',
                'verbose_name_plural': 'программы',
            },
        ),
    ]
