# Generated by Django 5.0.1 on 2024-01-31 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeProgramms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeProgramms', models.CharField(max_length=100, verbose_name='Тип программы')),
            ],
        ),
        migrations.AddField(
            model_name='programms',
            name='typeProgramm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='programms.typeprogramms', verbose_name='тип программы'),
        ),
    ]
