# Generated by Django 5.0.1 on 2024-01-31 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programms', '0002_typeprogramms_programms_typeprogramm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeprogramms',
            options={'verbose_name': 'тип программы', 'verbose_name_plural': 'типы программ'},
        ),
        migrations.RenameField(
            model_name='typeprogramms',
            old_name='typeProgramms',
            new_name='typePrograms',
        ),
    ]
