# Generated by Django 5.0.1 on 2024-02-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programms', '0004_rename_typeprograms_typeprogramms_typeprogramms'),
    ]

    operations = [
        migrations.AddField(
            model_name='programms',
            name='image',
            field=models.ImageField(null=True, upload_to='imageProgramms/', verbose_name='Изображение'),
        ),
    ]
